module.exports = {
    USERS             : 7,
    CUSTOMER_PAYMENTS   : 61,
    SUPPLIER_PAYMENTS   : 60,
    PERSONS           : 49,
    COMPANIES         : 50,
    LEADS             : 24,
    OPPORTUNITIES     : 25,
    PROJECTS          : 39,
    TASKS             : 40,
    EMPLOYEES         : 42,
    APPLICATIONS      : 43,
    JOBPOSITIONS      : 14,
    BIRTHDAYS         : 52,
    DEPARTMENTS       : 15,
    PROFILES          : 51,
    ORDERS            : 57,
    INVOICE           : 56,
    QUOTATIONS        : 55,
    DASHBOARD         : 29,
    PRODUCT           : 58,
    SALESQUOTATIONS   : 62,
    SALESORDERS       : 63,
    SALESINVOICES     : 64,
    SALESPRODUCT      : 65,
    WTRACK            : 75,
    PAYROLLEXPENSES   : 66,
    REVENUE           : 67,
    MONTHHOURS        : 68,
    BONUSTYPE         : 72,
    HOLIDAY           : 69,
    VACATION          : 70,
    ATTENDANCE        : 71,
    DASHBOARD_VACATION: 73,
    DASHBOARD_HR      : 74,
    EFFICIENCY        : 76,
    CAPACITY          : 77,
    JOBSDASHBOARD     : 80,
    PAYROLLPAYMENTS   : 79,
    PRODUCTSETTINGS   : 84,
    INVOICEAGING      : 82,
    CHARTOFACCOUNT    : 83,
    JOURNAL           : 85,
    JOURNALENTRY      : 86,
    INVOICECHARTS     : 87,
    SALARYREPORT      : 88,
    WORKFLOWS         : 44,
    DIVIDENDINVOICE   : 101,
    EXPENSESINVOICE   : 97,
    PROFORMA          : 99,
    CASHBOOK          : 105,
    CASHTRANSFER      : 106,
    WRITEOFF          : 107,
    DEALTASKS         : 110,
    CONTRACTJOBS      : 115,
    PROJECTSDASHBOARD : 116,
    FOLLOWERS         : 117,
	BUSITRIP          : 118,
    MANUALENTRY       : 119,
    PURCHASE_PAYMENTS : 109,
    ACCOUNTSCATEGORIES  : 122,
    ORDER               : 123,
    INVOICES            : 128,
    STOCKCORRECTIONS  : 125,
    PURCHASEORDERS    : 129,
    PURCHASEINVOICES  : 130,
    WAREHOUSE         : 132,
    REPORTS           : 141,
    INVENTORYREPORTS  : 146,
	PROJECTAPPROVAL   : 222,
    CHARGEITEMS       : 224,
    PROCESSCONTENTS   : 225,
    WORKORDERS        : 226,
    ORDERAPPROVAL     : 227,
    ORDERRECKONS      : 228,
    PIECEWAGES        : 229,
    PROCESSDETAILS    : 230,
    DESIGNREC         : 241,
    ASSIGN            : 242,
    ALUVENEERORDERS   : 243,
    BUILDINGCONTRACT  : 244,
    ALUORDERAPPROVAL  : 245,
	DESIGNPROJECT	  : 400,
	DESIGNBOOK		  : 401,
	PROJECTROYALTY    : 402,
	PROJECTFUND       : 403,
	ACCEPT            : 404,
	BANKINFO          : 405,
	FECERTIFICATE     : 406,
	BORROW			  : 407,
	MAKEINVOICE       : 408,
	JOURNALEXAMINE    : 409,
	TAXCATEGORIES     : 410,
	CASHDEPOSIT	      : 411,
	ENTERPRISE		  : 412,
	BUILDING: 413,
	PRODUCESCHEDULE: 414,
        PRODUCEMONITORING: 424,
	GOODSRETURN: 416,
	GOODSBARCODE: 417,
        GOODSSCRAP: 418,	
	OEMBARCODE: 419,
	COSTAPPORTIONMENT: 420,
	SCANLOGS: 421,
	COLORNUMBER: 422,
	ALUMINUMPRICE: 423,
        OEMORDERS: 292,
};
